# Generated by Django 3.2.12 on 2022-06-22 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('brand_name', models.CharField(max_length=250)),
                ('brand_code', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['-brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('category_name', models.CharField(max_length=300)),
                ('category_code', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['-section', '-category_name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('on_sale', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unit_price', models.FloatField()),
                ('quantity_added', models.FloatField(blank=True, null=True)),
                ('quantity_removed', models.FloatField(blank=True, null=True)),
                ('added_total', models.FloatField(blank=True, null=True)),
                ('opening_stock', models.FloatField(blank=True, default=0, null=True)),
                ('in_stock', models.FloatField(blank=True, null=True)),
                ('opening_total', models.FloatField(blank=True, default=0, null=True)),
                ('in_stock_total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('barcode', models.CharField(max_length=250)),
                ('item_code', models.CharField(blank=True, max_length=250, null=True)),
                ('item_name', models.CharField(blank=True, max_length=250, null=True)),
                ('make_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-item_name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('section_name', models.CharField(max_length=250)),
                ('section_code', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['-section_name'],
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('pushed_to_edi', models.BooleanField(default=False)),
                ('units_name', models.CharField(max_length=300)),
                ('units_code', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.ManyToManyField(to='debit.Category')),
            ],
            options={
                'ordering': ['-units_name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('quantity_of_available', models.FloatField(default=0)),
                ('quantity_on_deposit', models.FloatField(default=0)),
                ('quantity_total', models.FloatField(default=0)),
                ('total_of_available', models.FloatField(blank=True, null=True)),
                ('total_on_deposit', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('difference', models.FloatField(blank=True, null=True)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='debit.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('quantity', models.FloatField()),
                ('total', models.FloatField(blank=True, null=True)),
                ('sell_date', models.DateField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.item')),
            ],
            options={
                'ordering': ['-sell_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('product_code', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('quantity', models.FloatField(default=1)),
                ('slug', models.SlugField(max_length=1500)),
                ('status', models.CharField(blank=True, choices=[('AVAILABLE', 'AVAILABLE'), ('SOLD', 'SOLD'), ('DAMAGED', 'DAMAGED')], default='AVAILABLE', max_length=250, null=True)),
                ('is_on_sale', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemUnits',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('items_per_purchase_unit', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debit.item')),
                ('purchases_units', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_units', to='debit.units')),
                ('sales_units', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selling_units', to='debit.units')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('type_name', models.CharField(max_length=300)),
                ('type_code', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.category')),
            ],
            options={
                'ordering': ['-category', '-type_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('model_name', models.CharField(max_length=250)),
                ('model_code', models.CharField(blank=True, max_length=250, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.category')),
            ],
            options={
                'ordering': ['-model_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('hero_product_image', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debit.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('attribute_type', models.CharField(choices=[('SPECIAL OFFER', 'SPECIAL OFFER'), ('SPECIAL FEATURE', 'SPECIAL FEATURE'), ('SPECIFICATION', 'SPECIFICATION'), ('DESCRIPTION', 'DESCRIPTION')], max_length=300)),
                ('attribute_value', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debit.item')),
            ],
            options={
                'ordering': ['-attribute_type', '-attribute_value'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='debit.itemmodel'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.item'),
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.section'),
        ),
        migrations.AddField(
            model_name='brand',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.itemtype'),
        ),
    ]
