# Generated by Django 3.2.12 on 2022-06-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprisecontacts',
            old_name='franchise',
            new_name='enterprise',
        ),
        migrations.RenameField(
            model_name='enterprisecontacts',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
