# Generated by Django 3.2.12 on 2022-06-21 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_no',
        ),
        migrations.AddField(
            model_name='user',
            name='enterprise',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='guid',
            field=models.UUIDField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
