# Generated by Django 3.2.12 on 2022-06-22 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('marked_price', models.FloatField(blank=True, null=True)),
                ('discount_amount', models.FloatField(default=0)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('KSH', 'KSH'), ('USD', 'USD'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('AUD', 'AUD')], default='KSH', max_length=250)),
                ('quantity', models.FloatField(default=0)),
                ('on_display', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('pushed_to_edi', models.BooleanField(default=False)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='debit.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
