# Generated by Django 3.2.12 on 2022-04-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitelists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelist',
            old_name='franchise',
            new_name='enterprise',
        ),
    ]
